@host = https://localhost:7117

###

# Initiate Payment
# @name initiate_payment
POST {{host}}/payments HTTP/1.1
content-type: application/json

{
    "amount": 100,
    "currency": "EUR",
    "reference": "my reference"
}

###

@payment_id = {{initiate_payment.response.body.$.id}}

###

# Authorize (expects 0@{streamId} to exist)
POST {{host}}/payments/{{payment_id}}/authorize HTTP/1.1
content-type: application/json

###

# Refund (simply appends to stream regardless of state)
POST {{host}}/payments/{{payment_id}}/refunds HTTP/1.1
content-type: application/json

###

# Get Events
GET {{host}}/events/{{payment_id}} HTTP/1.1

###

# Get Events Backwards
GET {{host}}/events/{{payment_id}}?direction=Backwards HTTP/1.1

### Applications

# Initiate Onboarding Application
# @name initiate_application
POST {{host}}/onboarding/applications HTTP/1.1
content-type: application/json

{
    "first_name": "John",
    "last_name": "Doe",
    "email": "jdoe@gmail.com"
}

###

@application_id = {{initiate_application.response.body.$.id}}

# Start Application (filling in)
POST {{host}}/onboarding/applications/{{application_id}}/start HTTP/1.1
content-type: application/json

###

POST {{host}}/onboarding/applications/{{application_id}}/ubos HTTP/1.1
content-type: application/json

{
    "first_name": "Jane",
    "last_name": "Smith",
    "email": "jsmith@gmail.com"
}

###


# Get Events
GET {{host}}/events/{{application_id}} HTTP/1.1