@host = https://localhost:7117

###

# Initiate Payment
# @name initiate_payment
POST {{host}}/payments HTTP/1.1
content-type: application/json

{
    "amount": 100,
    "currency": "EUR",
    "reference": "my reference"
}


###

@payment_id = {{initiate_payment.response.body.$.id}}

###

# Authorize (expects 0@{streamId} to exist)
POST {{host}}/payments/{{payment_id}}/authorize HTTP/1.1
content-type: application/json

###

# Refund (simply appends to stream regardless of state)
POST {{host}}/payments/{{payment_id}}/refunds HTTP/1.1
content-type: application/json

###

# Get Events
GET {{host}}/events/{{payment_id}} HTTP/1.1
content-type: application/json

{
    "amount_minor": 100,
    "currency": "EUR",
    "reference": "ORD-12345"
}
